# Generated by Django 5.2.16 on 2026-07-31 15:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razón social"
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre comercial"
                    ),
                ),
                (
                    "rtn",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RTN del negocio"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo"
                    ),
                ),
                (
                    "invoice_regime",
                    models.CharField(
                        choices=[
                            ("cai", "Régimen por Imprenta (CAI)"),
                            ("cfe", "Factura Electrónica (CFE)"),
                        ],
                        default="cai",
                        max_length=10,
                        verbose_name="Régimen de facturación",
                    ),
                ),
                (
                    "cai_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Código CAI"
                    ),
                ),
                (
                    "establishment_code",
                    models.CharField(
                        default="001",
                        max_length=3,
                        verbose_name="Código de establecimiento",
                    ),
                ),
                (
                    "emission_point_code",
                    models.CharField(
                        default="001",
                        max_length=3,
                        verbose_name="Código de punto de emisión",
                    ),
                ),
                (
                    "document_type_code",
                    models.CharField(
                        default="01",
                        max_length=2,
                        verbose_name="Código de tipo de documento",
                    ),
                ),
                (
                    "range_start",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Correlativo inicial autorizado"
                    ),
                ),
                (
                    "range_end",
                    models.PositiveIntegerField(
                        default=10000, verbose_name="Correlativo final autorizado"
                    ),
                ),
                (
                    "next_correlative",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Próximo correlativo a emitir"
                    ),
                ),
                (
                    "emission_limit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha límite de emisión"
                    ),
                ),
                (
                    "default_isv_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="Tasa de ISV por defecto (%)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Configuración del negocio",
                "verbose_name_plural": "Configuración del negocio",
            },
        ),
    ]
