# Generated by Django 5.2.16 on 2026-07-31 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Creó"),
                            ("updated", "Modificó"),
                            ("deleted", "Eliminó"),
                        ],
                        max_length=10,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Tipo de registro"),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=255, verbose_name="Registro"),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, max_length=50, verbose_name="ID"),
                ),
                (
                    "extra",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Detalle"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Bitácora de auditoría",
                "ordering": ["-created_at"],
            },
        ),
    ]
