# Generated by Django 5.2.16 on 2026-07-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="auto_print_on_sale",
            field=models.BooleanField(
                default=True,
                verbose_name="Imprimir automáticamente al cobrar una venta",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="receipt_format",
            field=models.CharField(
                choices=[
                    ("thermal_80", "Térmica 80mm"),
                    ("thermal_58", "Térmica 58mm"),
                    ("letter", "Matriz de puntos / carta"),
                ],
                default="thermal_80",
                max_length=15,
                verbose_name="Formato de impresión de ticket",
            ),
        ),
    ]
