# Generated by Django 5.2.16 on 2026-08-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_role_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contingency_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Usar rango de contingencia sin internet"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contingency_next_correlative",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Próximo correlativo de contingencia",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contingency_range_end",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Correlativo final de contingencia"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contingency_range_start",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Correlativo inicial de contingencia",
            ),
        ),
    ]
