# Generated by Django 5.2.16 on 2026-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_company_contingency_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="electronic_invoicing_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Actívalo solo cuando tengas las credenciales de un proveedor certificado por el SAR.",
                verbose_name="Conectar un proveedor de facturación electrónica (DTE)",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="psa_api_key",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Clave / token de acceso"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="psa_api_url",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="URL del webservice del proveedor",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="psa_provider_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Proveedor certificado (PSA)"
            ),
        ),
    ]
