# Generated by Django 5.2.16 on 2026-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="document",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="RTN / No. de Identidad"
            ),
        ),
    ]
