# Generated by Django 5.2.16 on 2026-08-19 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto máximo que este cliente puede deber. Déjalo en 0 para no permitirle comprar al crédito.",
                max_digits=12,
                verbose_name="Límite de crédito (fiado)",
            ),
        ),
        migrations.CreateModel(
            name="CreditPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto abonado"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta", "Tarjeta"),
                            ("transferencia", "Transferencia"),
                        ],
                        default="efectivo",
                        max_length=20,
                        verbose_name="Forma de pago",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="Notas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_payments",
                        to="clients.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono a cuenta",
                "verbose_name_plural": "Abonos a cuenta",
                "ordering": ["-created_at"],
            },
        ),
    ]
