# Generated by Django 5.2.16 on 2026-07-31 15:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Código de barras",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de vencimiento"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="15% para la mayoría de productos, 18% para bebidas alcohólicas y tabaco.",
                max_digits=5,
                verbose_name="Tasa de ISV (%)",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="reason_category",
            field=models.CharField(
                choices=[
                    ("compra", "Compra / reabastecimiento"),
                    ("venta", "Venta"),
                    ("merma", "Merma"),
                    ("dano", "Producto dañado"),
                    ("robo", "Robo / faltante"),
                    ("devolucion", "Devolución de cliente"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=15,
                verbose_name="Categoría de motivo",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Detalle del motivo"
            ),
        ),
    ]
