# Generated by Django 5.2.16 on 2026-08-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_barcode_product_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="wholesale_min_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="A partir de esta cantidad se aplica automáticamente el precio de mayoreo en el POS.",
                max_digits=10,
                null=True,
                verbose_name="Cantidad mínima de mayoreo",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio por unidad cuando se compra desde la cantidad mínima de mayoreo. Déjalo vacío para no ofrecer mayoreo.",
                max_digits=10,
                null=True,
                verbose_name="Precio de mayoreo",
            ),
        ),
    ]
