# Generated by Django 5.2.16 on 2026-08-27 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_purchaseorder_purchaseorderitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("abierto", "Abierto"), ("cerrado", "Cerrado")],
                        default="abierto",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="Notas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Cerrado"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteo físico de inventario",
                "verbose_name_plural": "Conteos físicos de inventario",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Stock en sistema"
                    ),
                ),
                (
                    "counted_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Stock contado",
                    ),
                ),
                (
                    "inventory_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inventorycount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_items",
                        to="inventory.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de conteo",
                "verbose_name_plural": "Detalles de conteo",
                "ordering": ["product__name"],
            },
        ),
    ]
