# Generated by Django 5.2.16 on 2026-08-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_inventorycount_inventorycountitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="No es obligatorio que sea único: a veces el mismo código de barras se repite en variantes de empaque del mismo proveedor.",
                max_length=64,
                null=True,
                verbose_name="Código de barras",
            ),
        ),
    ]
