# Generated by Django 5.2.16 on 2026-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_product_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycount",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Si no eliges ninguna, el conteo incluye todas las categorías.",
                related_name="inventory_counts",
                to="inventory.category",
                verbose_name="Categorías",
            ),
        ),
    ]
