# Generated by Django 5.2.16 on 2026-09-11 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_purchaseorderpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cantidad recibida en este lote",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de vencimiento del lote",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="Notas"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recibido"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="inventory.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="inventory.purchaseorderitem",
                        verbose_name="Línea de orden de compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de producto",
                "verbose_name_plural": "Lotes de producto",
                "ordering": ["expiration_date", "-received_at"],
            },
        ),
    ]
