# Generated by Django 5.2.16 on 2026-07-31 15:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                max_digits=5,
                verbose_name="Tasa de ISV (%)",
            ),
        ),
        migrations.CreateModel(
            name="CashSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Apertura"),
                ),
                (
                    "opening_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto inicial",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Cierre"),
                ),
                (
                    "counted_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto contado al cierre",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto esperado",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Diferencia",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="Notas"),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_sessions_closed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cerrada por",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_sessions_opened",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Abierta por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de caja",
                "verbose_name_plural": "Sesiones de caja",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="cash_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="sales.cashsession",
                verbose_name="Sesión de caja",
            ),
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="No. de nota de crédito",
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="Motivo")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuesto",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="sales.sale",
                        verbose_name="Venta original",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de crédito",
                "verbose_name_plural": "Notas de crédito",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditNoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cantidad devuelta",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio unitario"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="Tasa de ISV (%)",
                    ),
                ),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.creditnote",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note_items",
                        to="sales.saleitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de nota de crédito",
                "verbose_name_plural": "Detalles de nota de crédito",
            },
        ),
    ]
