# Generated by Django 5.2.16 on 2026-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_saleitem_tax_rate_cashsession_sale_cash_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("transferencia", "Transferencia"),
                    ("credito", "Crédito (fiado)"),
                ],
                default="efectivo",
                max_length=20,
                verbose_name="Forma de pago",
            ),
        ),
    ]
