# Generated by Django 5.2.16 on 2026-08-27 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_sale_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeldSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ID de cliente (crudo)"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Cliente"
                    ),
                ),
                (
                    "client_rtn",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="RTN del cliente"
                    ),
                ),
                (
                    "new_client_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Nombre de cliente nuevo",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Forma de pago"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="Notas"),
                ),
                ("cart_json", models.TextField(verbose_name="Carrito (JSON)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Puesta en espera"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="held_sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cajero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta en espera",
                "verbose_name_plural": "Ventas en espera",
                "ordering": ["-created_at"],
            },
        ),
    ]
