# Generated by Django 5.2.16 on 2026-08-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_heldsale"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="mixed_cash_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Monto en efectivo (pago mixto)",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="mixed_other_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Monto en otro método (pago mixto)",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("transferencia", "Transferencia"),
                    ("credito", "Crédito (fiado)"),
                    ("mixto", "Mixto (efectivo + otro)"),
                ],
                default="efectivo",
                max_length=20,
                verbose_name="Forma de pago",
            ),
        ),
    ]
