# Generated by Django 5.2.16 on 2026-08-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_sale_mixed_cash_amount_sale_mixed_other_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount_authorized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorized_discounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Descuento autorizado por",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Descuento (%)"
            ),
        ),
    ]
