# Generated by Django 5.2.16 on 2026-08-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_sale_discount_authorized_by_sale_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_contingency",
            field=models.BooleanField(
                default=False,
                help_text="La venta se facturó sin conexión usando el rango de contingencia y se sincronizó después.",
                verbose_name="Emitida en contingencia (sin internet)",
            ),
        ),
    ]
