# Generated by Django 5.2.16 on 2026-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_sale_is_contingency"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="dte_qr_data",
            field=models.TextField(
                blank=True, verbose_name="Contenido del código QR del DTE"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="dte_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Enviada al SAR"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="dte_status",
            field=models.CharField(
                choices=[
                    ("no_aplica", "No aplica (régimen CAI impreso)"),
                    ("sin_conectar", "Sin proveedor certificado conectado"),
                    ("pendiente", "Pendiente de envío al SAR"),
                    ("enviada", "Enviada al proveedor certificado"),
                    ("aceptada", "Aceptada por el SAR"),
                    ("rechazada", "Rechazada por el SAR"),
                ],
                default="no_aplica",
                max_length=15,
                verbose_name="Estado de facturación electrónica",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="dte_uuid",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Clave del DTE"
            ),
        ),
    ]
